### PR TITLE
feat: fix bug that the first AI message cannot be regenerated

### LINKED ISSUE #916: [bug] the first AI message cannot be regenerated
See: https://ai.casbin.com/

https://github.com/user-attachments/assets/d6729925-9644-4894-b58b-1eb5d9d2ebae

The frontend crashes at code:

image

### PR DESCRIPTION
**Pull request by MartinRepo**
fix: #916

### CODE REVIEW

File: controllers/message.go [hunk 1]
```diff
@@ -153,12 +153,20 @@ func (c *ApiController) AddMessage() {
...
+	if err != nil {
+		c.ResponseError(err.Error())
+		return
+	}
+
+	if message.IsRegenerated && len(messages) == 1 && messages[0].ReplyTo == "Welcome" && messages[0].Author == "AI" {
+		object.DeleteMessage(messages[0])
+		message.Author = "AI"
+		message.ReplyTo = "Welcome"
+		addMessageAfterSuccess = false
```
Comment (hsluoyz) [inline controllers/message.go]: if doesn't need, just return

File: controllers/message.go [hunk 2]
```diff
@@ -153,12 +153,20 @@ func (c *ApiController) AddMessage() {
...
 	}
-	if message.IsRegenerated {
-		messages, err := object.GetChatMessages(message.Chat)
-		if err != nil {
-			c.ResponseError(err.Error())
-			return
-		}
+
+	addMessageAfterSuccess := true
+	messages, err := object.GetChatMessages(message.Chat)
```
Comment (hsluoyz) [inline controllers/message.go]: Why move out?

File: web/src/ChatBox.js [hunk 3]
```diff
@@ -70,7 +70,13 @@ class ChatBox extends React.Component {
...
   handleRegenerate = () => {
-    const lastUserMessage = this.props.messages.reverse().find(message => message.author !== "AI");
+    const messages = this.props.messages;
+    if (messages.length === 1 && messages[0].replyTo === "Welcome" && messages[0].author === "AI") {
+      this.props.sendMessage("", "", true);
+      return;
+    }
+
+    const lastUserMessage = messages.reverse().find(message => message.author !== "AI");
     this.props.sendMessage(lastUserMessage.text, "", true);
```
Comment (hsluoyz) [inline web/src/ChatBox.js]: Do you really use `lastUserMessage.text`? Why not just use `this.props.sendMessage("Casibase##RegenerateFlag", "", true);`?

File: controllers/message.go [hunk 4]
```diff
@@ -224,7 +232,7 @@ func (c *ApiController) AddMessage() {
 		return
 	}
 
-	if success {
+	if success && addMessageAfterSuccess {
```
Comment (hsluoyz) [inline controllers/message.go:246]: Why not return early?

**Review by hsluoyz — CHANGES_REQUESTED** [review]

File: controllers/message.go [hunk 5]
```diff
@@ -153,12 +153,20 @@ func (c *ApiController) AddMessage() {
...
+
+	addMessageAfterSuccess := true
+	messages, err := object.GetChatMessages(message.Chat)
+	if err != nil {
+		c.ResponseError(err.Error())
+		return
+	}
+
+	if message.IsRegenerated && len(messages) == 1 && messages[0].ReplyTo == "Welcome" && messages[0].Author == "AI" {
+		object.DeleteMessage(messages[0])
```
Comment (hsluoyz) [inline controllers/message.go]: Handle error

**Review by hsluoyz — CHANGES_REQUESTED** [review]

File: controllers/message.go (hunk 1 above)
Comment (MartinRepo) [reply controllers/message.go]: After this it's still necessary to run object.AddMessage() one more time.

File: web/src/ChatBox.js (hunk 3 above)
Comment (MartinRepo) [reply web/src/ChatBox.js]: Yes, it is required. In ChatPage.js, sendMessage() function, it needs text to generate a new message struct.

File: controllers/message.go (hunk 2 above)
Comment (MartinRepo) [reply controllers/message.go]: make sense, discarded this change

File: controllers/message.go (hunk 5 above)
Comment (MartinRepo) [reply controllers/message.go]: make sense, handled

File: controllers/message.go (hunk 4 above)
Comment (MartinRepo) [reply controllers/message.go:246]: We need to execute object.AddMessage() at line 240. However, object.AddMessage() at line 267 shouldn't be executed.  We could just RETURN after line 240, but it would require "if" block one more time, and I guess that's not as clean as this.

**Review by hsluoyz — APPROVED** [review]
