### PR TITLE
feat: fix the issue that DALL-E returned image URL is expired

### LINKED ISSUE #945: [bug] the DALL-E returned image URL is expired
The DALL-E returned image URL is something like: https://oaidalleapiprodscus.blob.core.windows.net/private/ . This image should be stored to Casibase's file storage (like uploaded image).

image

### PR DESCRIPTION
**Pull request by MartinRepo**
fix: #945

### CODE REVIEW

File: controllers/message_util.go [hunk 1]
```diff
@@ -286,3 +286,22 @@ func getPromptIntention(prompt string, name string) (string, error) {
 	intention := writer.String()
 	return intention, nil
 }
+
+func storeDALLEImgae(chat string, origin string) (bool, error) {
+	messages, err := object.GetChatMessages(chat)
```
Comment (hsluoyz) [inline controllers/message_util.go]: only handle the current answer, why fetch old messages?

File: controllers/message_util.go [hunk 2]
```diff
@@ -286,3 +286,22 @@ func getPromptIntention(prompt string, name string) (string, error) {
...
+	if err != nil {
+		return false, err
+	}
+	answerMessage := messages[len(messages)-1]
+	answerMessage.FileName = answerMessage.Name + ".jpg"
+
+	err = object.RefineMessageFiles(answerMessage, origin)
```
Comment (hsluoyz) [inline controllers/message_util.go]: RefineMessageFiles handle data:image, does DALLE return data:image?

File: controllers/message_util.go [hunk 3]
```diff
@@ -286,3 +286,22 @@ func getPromptIntention(prompt string, name string) (string, error) {
...
 	return intention, nil
 }
+
+func storeDALLEImgae(chat string, origin string) (bool, error) {
+	messages, err := object.GetChatMessages(chat)
+	if err != nil {
+		return false, err
+	}
+	answerMessage := messages[len(messages)-1]
+	answerMessage.FileName = answerMessage.Name + ".jpg"
```
Comment (hsluoyz) [inline controllers/message_util.go]: Must it be jpg? Not png?

File: model/local.go [hunk 4]
```diff
@@ -287,7 +287,8 @@ func (p *LocalModelProvider) QueryText(question string, writer io.Writer, histor
 				return nil, err
 			}
 
-			url := fmt.Sprintf("<img src=\"%s\" width=\"100%%\" height=\"auto\">", respUrl.Data[0].URL)
+			base64Image, err := getImageRefinedText(respUrl.Data[0].URL)
```
Comment (hsluoyz) [inline model/local.go]: Why change here? Why not handle error?

File: controllers/message_answer.go [hunk 5]
```diff
@@ -254,6 +254,16 @@ func (c *ApiController) GetMessageAnswer() {
 		return
 	}
 
+	if modelProvider == "dall-e-3" {
+		host := c.Ctx.Request.Host
+		origin := getOriginFromHost(host)
+		success, err := storeDALLEImgae(chat.Name, origin)
+		if !success {
```
Comment (hsluoyz) [inline controllers/message_answer.go]: Inside if, should always be `if err != nil {`

File: controllers/message_util.go [hunk 6]
```diff
@@ -286,3 +286,22 @@ func getPromptIntention(prompt string, name string) (string, error) {
 	intention := writer.String()
 	return intention, nil
 }
+
+func storeDALLEImgae(chat string, origin string) (bool, error) {
```
Comment (hsluoyz) [inline controllers/message_util.go]: No DALLE in function name

**Review by hsluoyz — CHANGES_REQUESTED** [review]

**Review by hsluoyz — APPROVED** [review]
