### PR TITLE
feat: fix bug that the chat user avatar can't load correctly

### LINKED ISSUE #1063: [bug] the right-side avatar should be chat user's avatar instead of logged-in user's (aka admin)
See: https://ai-admin.casibase.com/chats

Image

### PR DESCRIPTION
**Pull request by dark-Qy**
Fix: https://github.com/casibase/casibase/issues/1063

### CODE REVIEW

File: web/src/chat/MessageItem.js [hunk 1]
```diff
@@ -189,7 +190,7 @@ const MessageItem = ({
             interval: 50,
           } : undefined}
           avatar={{
-            src: message.author === "AI" ? avatar : account.avatar,
+            src: message.author === "AI" ? avatar : getUserAvatar(message, account),
```
Comment (hsluoyz) [inline web/src/chat/MessageItem.js]: Setting.getUserAvatar

File: web/package.json [hunk 2]
```diff
@@ -24,9 +24,11 @@
     "guacamole-common-js": "^1.5.0",
     "highlight.js": "^11.9.0",
     "i18next": "^19.8.9",
+    "identicon.js": "^2.3.3",
```
Comment (hsluoyz) [inline web/package.json:27]: yarn.lock should be updated

File: web/src/Conf.js [hunk 3]
```diff
@@ -43,3 +43,5 @@ export const ThemeDefault = {
   borderRadius: 6,
   isCompact: false,
 };
+
+export const AvatarErrorUrl = "https://cdn.casbin.com/avatar-pool/error.png";
```
Comment (hsluoyz) [inline web/src/Conf.js]: Use: https://github.com/casibase/static

File: web/src/Setting.js [hunk 4]
```diff
@@ -67,6 +68,36 @@ export function getMyProfileUrl(account) {
...
+    if (lastSlashIndex !== -1) {
+      // Get the base URL
+      const baseUrl = account.avatar.substring(0, lastSlashIndex + 1);
+      return `${baseUrl}${message.author}.png`;
+    }
+  }
+
+  try {
+    // If message author does not have an avatar, generate an Identicon
+    const identicon = new Identicon(md5(message.author), 420);
```
Comment (hsluoyz) [inline web/src/Setting.js]: Use it as Casnode:

image

File: web/src/Setting.js [hunk 5]
```diff
@@ -67,6 +68,36 @@ export function getMyProfileUrl(account) {
   return getUrlWithLanguage(CasdoorSdk.getMyProfileUrl(account));
 }
 
+export function getUserAvatar(message, account) {
+  if (message.author === "AI") {
+    return AiAvatar;
+  }
+
+  // For current user messages, use their avatar
+  if (message.author === account.name && message.organization === account.owner) {
```
Comment (hsluoyz) [inline web/src/Setting.js]: Is this needed?

File: web/src/Setting.js [hunk 6]
```diff
@@ -67,6 +68,36 @@ export function getMyProfileUrl(account) {
...
+  }
+
+  // If account exists and has an avatar, construct URL for other users
+  if (account && account.avatar) {
+    // Find the last slash position
+    const lastSlashIndex = account.avatar.lastIndexOf("/");
+    if (lastSlashIndex !== -1) {
+      // Get the base URL
+      const baseUrl = account.avatar.substring(0, lastSlashIndex + 1);
+      return `${baseUrl}${message.author}.png`;
```
Comment (hsluoyz) [inline web/src/Setting.js]: Don't hard code .png

**Review by hsluoyz — CHANGES_REQUESTED** [review]
