### PR TITLE
feat: fix maxTokens for CohereModelProvider

### LINKED ISSUE #741: Does Cohere's CohereDefaultMaxTokens = 256 actually work for most cases?
image

### PR DESCRIPTION
**Pull request by TravisRoad**
Fix: #741
- set default maxTokens to 4096
- decide the `maxTokens` value according to the model's context window size

### CODE REVIEW

File: model/cohere.go [hunk 1]
```diff
@@ -92,18 +99,30 @@ func (p *CohereModelProvider) calculatePrice(modelResult *ModelResult) error {
 	return nil
 }
 
+func (p *CohereModelProvider) getMaxTokens(model string) int {
+	if p.maxTokens > 0 {
+		return p.maxTokens
+	}
+	if val, ok := CohereModelMaxTokens[model]; ok {
+		return val
+	}
```
Comment (hsluoyz) [inline model/cohere.go:108]: error handling

**Review by hsluoyz — CHANGES_REQUESTED** [review]

**Review by hsluoyz — APPROVED** [review]
